name: Install

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Remove "safe to test" label, if PR is from a fork
        uses: nilsreichardt/remove-safe-to-test-label@0a57536fd060d0ab87f100745b5bb96b6301588c

      - name: Ensure PR has "safe to test" label, if PR is from a fork
        uses: nilsreichardt/verify-safe-to-test-label@bf23206df73cefc6c47aec20af24938b5665f78f
    
      - name: Checkout base code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Insatll
        run: |
          python main.py
