name: Install

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]

jobs:
  authenticate:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Ensure PR has "safe to test" label, if PR is from a fork
        uses: nilsreichardt/verify-safe-to-test-label@d99b8b2019308188eb7c0f332f9ab02932f58cc8

  install:
    needs: authenticate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Insatll
        run: |
          python main.py
