name: Install

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]

jobs:
  install:
    runs-on: ubuntu-latest
    # permissions:
      # contents: read
      # pull-requests: write
    steps:
      - name: Remove "safe to test" label, if PR is from a fork
        uses: nilsreichardt/remove-safe-to-test-label@b33cbd9ddfc6ed29086c2542c0e79f0cd3095460

      - name: Ensure PR has "safe to test" label, if PR is from a fork
        uses: nilsreichardt/verify-safe-to-test-label@1d027afe611c51da9fcab7583e1b0946e1386144
    
      - name: Checkout base code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Insatll
        run: |
          python main.py
